version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    groups:
      k8s-deps:
        patterns:
          - "k8s.io/*"
      go-deps:
        exclude-patterns:
          - "k8s.io/*"
        update-types:
          - minor
          - patch
    cooldown:
      default-days: 7
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-deps:
        patterns:
          - "*"
    cooldown:
      default-days: 7
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
